[project]
name = "ai-meme-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pillow>=11.2.1",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.2",
]
